global using AtencionMedica.Infraestructure;
global using Microsoft.AspNetCore.Mvc;
global using System.Net;
global using AutoMapper;
global using AtencionMedica.Domain.Entities;
global using AtencionMedica.Domain.CustomEntities;
global using AtencionMedica.WebApi.Responses;
global using AtencionMedica.Application.Interfaces;
global using AtencionMedica.Application.DTOs;