namespace AtencionMedica.Infraestructure.Seeders
{
    internal class SeedComuna : ISeed<Comuna>
    {
        public void Seed(ModelBuilder modelBuilder)
        {
            Comuna[] hasData = {
                new Comuna { Id = 1, NombreComuna = "Arica", Region = "Región de Tarapacá", SiglaRegion = "I", EsActivo = true},
                new Comuna { Id = 2, NombreComuna = "Camarones", Region = "Región de Tarapacá", SiglaRegion = "I", EsActivo = true},
                new Comuna { Id = 3, NombreComuna = "Alto Hospicio", Region = "Región de Antofagasta", SiglaRegion = "II", EsActivo = true},
                new Comuna { Id = 4, NombreComuna = "Iquique", Region = "Región de Antofagasta", SiglaRegion = "II", EsActivo = true},
                new Comuna { Id = 5, NombreComuna = "Camiña", Region = "Región de Antofagasta", SiglaRegion = "II", EsActivo = true},
                new Comuna { Id = 6, NombreComuna = "Colchane", Region = "Región de Antofagasta", SiglaRegion = "II", EsActivo = true},
                new Comuna { Id = 7, NombreComuna = "Huara", Region = "Región de Antofagasta", SiglaRegion = "II", EsActivo = true},
                new Comuna { Id = 8, NombreComuna = "Pica", Region = "Región de Antofagasta", SiglaRegion = "II", EsActivo = true},
                new Comuna { Id = 9, NombreComuna = "Pozo Almonte", Region = "Región de Antofagasta", SiglaRegion = "II", EsActivo = true},
                new Comuna { Id = 10, NombreComuna = "Caldera", Region = "Región de Atacama", SiglaRegion = "III", EsActivo = true},
                new Comuna { Id = 11, NombreComuna = "Chanaral", Region = "Región de Atacama", SiglaRegion = "III", EsActivo = true},
                new Comuna { Id = 12, NombreComuna = "Copiapó", Region = "Región de Atacama", SiglaRegion = "III", EsActivo = true},
                new Comuna { Id = 13, NombreComuna = "Diego de Almagro", Region = "Región de Atacama", SiglaRegion = "III", EsActivo = true},
                new Comuna { Id = 14, NombreComuna = "Freirina", Region = "Región de Atacama", SiglaRegion = "III", EsActivo = true},
                new Comuna { Id = 15, NombreComuna = "Huasco", Region = "Región de Atacama", SiglaRegion = "III", EsActivo = true},
                new Comuna { Id = 16, NombreComuna = "Tierra Amarilla", Region = "Región de Atacama", SiglaRegion = "III", EsActivo = true},
                new Comuna { Id = 17, NombreComuna = "Vallenar", Region = "Región de Atacama", SiglaRegion = "III", EsActivo = true},
                new Comuna { Id = 18, NombreComuna = "Andacollo", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { Id = 19, NombreComuna = "Canela", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { Id = 20, NombreComuna = "Combarbalá", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},

                new Comuna { Id = 21, NombreComuna = "Coquimbo", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { Id = 22, NombreComuna = "Illapel", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { Id = 23, NombreComuna = "La Higuera", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { Id = 24, NombreComuna = "La Serena", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { Id = 25, NombreComuna = "Los Vilos", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { Id = 26, NombreComuna = "Monte Patria", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { Id = 27, NombreComuna = "Ovalle", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { Id = 28, NombreComuna = "Paihuano", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { Id = 29, NombreComuna = "Punitaqui", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { Id = 30, NombreComuna = "Río Hurtado", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { Id = 31, NombreComuna = "Salamanca", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { Id = 32, NombreComuna = "Vicuña", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { Id = 33, NombreComuna = "Algarrobo", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 34, NombreComuna = "Cabildo", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 35, NombreComuna = "Calera", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 36, NombreComuna = "Calle Larga", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 37, NombreComuna = "Cartagena", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 38, NombreComuna = "Casablanca", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 39, NombreComuna = "Catemu", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 40, NombreComuna = "Concón", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},

                new Comuna { Id = 41, NombreComuna = "El Quisco", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 42, NombreComuna = "El Tabo", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 43, NombreComuna = "Hijuelas", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 44, NombreComuna = "Isla de Pascua", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 45, NombreComuna = "Juan Fernández", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 46, NombreComuna = "La Cruz", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 47, NombreComuna = "La Ligua", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 48, NombreComuna = "Limache", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 49, NombreComuna = "Llaillay", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 50, NombreComuna = "Los Andes", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 51, NombreComuna = "Nogales", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 52, NombreComuna = "Olmué", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 53, NombreComuna = "Panquehue", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 54, NombreComuna = "Papudo", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 55, NombreComuna = "Petorca", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 56, NombreComuna = "Puchuncaví", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 57, NombreComuna = "Putaendo", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 58, NombreComuna = "Quillota", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 59, NombreComuna = "Quilpué", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 60, NombreComuna = "Quintero", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 61, NombreComuna = "Rinconada", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 62, NombreComuna = "San Antonio", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 63, NombreComuna = "San Esteban", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 64, NombreComuna = "San Felipe", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 65, NombreComuna = "Santa María", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 66, NombreComuna = "Santo Domingo", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 67, NombreComuna = "Valparaíso", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 68, NombreComuna = "Villa Alemana", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 69, NombreComuna = "Viña del Mar", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 70, NombreComuna = "Zapallar", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { Id = 71, NombreComuna = "Alhué", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 72, NombreComuna = "Buin", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 73, NombreComuna = "Calera de Tango", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 74, NombreComuna = "Cerrillos", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 75, NombreComuna = "Cerro Navia", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 76, NombreComuna = "Colina", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 77, NombreComuna = "Conchalí", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 78, NombreComuna = "Curacaví", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 79, NombreComuna = "El Bosque", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 80, NombreComuna = "El Monte", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 81, NombreComuna = "Estación Central", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 82, NombreComuna = "Huechuraba", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 83, NombreComuna = "Independencia", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 84, NombreComuna = "Isla de Maipo", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 85, NombreComuna = "La Cisterna", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 86, NombreComuna = "La Florida", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 87, NombreComuna = "La Granja", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 88, NombreComuna = "La Pintana", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 89, NombreComuna = "La Reina", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 90, NombreComuna = "Lampa", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 91, NombreComuna = "Las Condes", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 92, NombreComuna = "Lo Barnechea", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 93, NombreComuna = "Lo Espejo", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 94, NombreComuna = "Lo Prado", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 95, NombreComuna = "Macul", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 96, NombreComuna = "Maipú", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 97, NombreComuna = "María Pinto", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 98, NombreComuna = "Melipilla", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 99, NombreComuna = "Ñuñoa", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 100, NombreComuna = "Padre Hurtado", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},

                new Comuna { Id = 101, NombreComuna = "Paine", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 102, NombreComuna = "Pedro Aguirre Cerda", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 103, NombreComuna = "Peñaflor", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 104, NombreComuna = "Peñalolén", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 105, NombreComuna = "Pirque", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 106, NombreComuna = "Providencia", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 107, NombreComuna = "Pudahuel", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 108, NombreComuna = "Puente Alto", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 109, NombreComuna = "Quilicura", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 110, NombreComuna = "Quinta Normal", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 111, NombreComuna = "Recoleta", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 112, NombreComuna = "Renca", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 113, NombreComuna = "San Bernardo", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 114, NombreComuna = "San Joaquín", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 115, NombreComuna = "San José de Maipo", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 116, NombreComuna = "San Miguel", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 117, NombreComuna = "San Pedro", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 118, NombreComuna = "San Ramón", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 119, NombreComuna = "Santiago", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 120, NombreComuna = "Talagante", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 121, NombreComuna = "Tiltil", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 122, NombreComuna = "Vitacura", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { Id = 123, NombreComuna = "Cachapoal", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 124, NombreComuna = "Cardenal Caro", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 125, NombreComuna = "Chépica", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 126, NombreComuna = "Chimbarongo", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 127, NombreComuna = "Codegua", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 128, NombreComuna = "Coinco", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 129, NombreComuna = "Coltauco", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 130, NombreComuna = "Doñihue", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 131, NombreComuna = "Graneros", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 132, NombreComuna = "La Estrella", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 133, NombreComuna = "Las Cabras", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 134, NombreComuna = "Litueche", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 135, NombreComuna = "Lolol", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 136, NombreComuna = "Machalí", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 137, NombreComuna = "Malloa", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 138, NombreComuna = "Marchihue", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 139, NombreComuna = "Nancagua", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 140, NombreComuna = "Navidad", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 141, NombreComuna = "Olivar", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 142, NombreComuna = "Palmilla", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 143, NombreComuna = "Paredones", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 144, NombreComuna = "Peralillo", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 145, NombreComuna = "Peumo", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 146, NombreComuna = "Pichidegua", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 147, NombreComuna = "Pichilemu", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 148, NombreComuna = "Placilla", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 149, NombreComuna = "Pumanque", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 150, NombreComuna = "Quinta de Tilcoco", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 151, NombreComuna = "Rancagua", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 152, NombreComuna = "Rengo", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 153, NombreComuna = "Requínoa", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 154, NombreComuna = "San Fernando", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 155, NombreComuna = "San Vicente de Tagua Tagua", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 156, NombreComuna = "Santa Cruz", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { Id = 157, NombreComuna = "Cauquenes", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 158, NombreComuna = "Chanco", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 159, NombreComuna = "Colbún", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 160, NombreComuna = "Constitución", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 161, NombreComuna = "Curepto", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 162, NombreComuna = "Curicó", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 163, NombreComuna = "Empedrado", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 164, NombreComuna = "Hualañé", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 165, NombreComuna = "Licantén", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 166, NombreComuna = "Linares", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 167, NombreComuna = "Longaví", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 168, NombreComuna = "Maule", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 169, NombreComuna = "Molina", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 170, NombreComuna = "Parral", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 171, NombreComuna = "Pelarco", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 172, NombreComuna = "Pelluhue", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 173, NombreComuna = "Pencahue", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 174, NombreComuna = "Rauco", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 175, NombreComuna = "Retiro", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 176, NombreComuna = "Romeral", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 177, NombreComuna = "Sagrada Familia", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 178, NombreComuna = "San Clemente", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 179, NombreComuna = "San Javier", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 180, NombreComuna = "San Rafael", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 181, NombreComuna = "Santa Cruz", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 182, NombreComuna = "Talca", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 183, NombreComuna = "Teno", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 184, NombreComuna = "Vichuquén", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 185, NombreComuna = "Villa Alegre", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 186, NombreComuna = "Yerbas Buenas", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { Id = 187, NombreComuna = "Alto Biobío", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 188, NombreComuna = "Antuco", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 189, NombreComuna = "Arauco", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 190, NombreComuna = "Bulnes", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},

                new Comuna { Id = 191, NombreComuna = "Cabrero", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 192, NombreComuna = "Cañete", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 193, NombreComuna = "Chiguayante", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 194, NombreComuna = "Chillán", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 195, NombreComuna = "Chillán Viejo", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 196, NombreComuna = "Cobquecura", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 197, NombreComuna = "Coelemu", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 198, NombreComuna = "Coihueco", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 199, NombreComuna = "Concepción", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 200, NombreComuna = "Contulmo", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 201, NombreComuna = "Coronel", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 202, NombreComuna = "Curanilahue", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 203, NombreComuna = "El Carmen", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 204, NombreComuna = "Florida", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 205, NombreComuna = "Hualpén", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 206, NombreComuna = "Hualqui", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 207, NombreComuna = "Laja", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 208, NombreComuna = "Lebu", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 209, NombreComuna = "Los Álamos", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 210, NombreComuna = "Los Ángeles", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},

                new Comuna { Id = 211, NombreComuna = "Lota", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 212, NombreComuna = "Mulchén", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 213, NombreComuna = "Nacimiento", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 214, NombreComuna = "Negrete", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 215, NombreComuna = "Ninhue", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 216, NombreComuna = "Ñiquén", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 217, NombreComuna = "Pemuco", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 218, NombreComuna = "Penco", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 219, NombreComuna = "Pinto", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 220, NombreComuna = "Portezuelo", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 221, NombreComuna = "Quilaco", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 222, NombreComuna = "Quilleco", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 223, NombreComuna = "Quillón", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 224, NombreComuna = "Quirihue", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 225, NombreComuna = "Ránquil", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 226, NombreComuna = "San Carlos", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 227, NombreComuna = "San Fabián", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 228, NombreComuna = "San Ignacio", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 229, NombreComuna = "San Nicolás", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 230, NombreComuna = "San Pedro de la Paz", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 231, NombreComuna = "San Rosendo", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 232, NombreComuna = "Santa Bárbara", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 233, NombreComuna = "Santa Juana", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 234, NombreComuna = "Talcahuano", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 235, NombreComuna = "Tirúa", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 236, NombreComuna = "Tomé", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 237, NombreComuna = "Treguaco", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 238, NombreComuna = "Tucapel", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 239, NombreComuna = "Yumbel", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 240, NombreComuna = "Yungay", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { Id = 241, NombreComuna = "Angol", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 242, NombreComuna = "Carahue", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 243, NombreComuna = "Cholchol", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 244, NombreComuna = "Collipulli", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 245, NombreComuna = "Cunco", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 246, NombreComuna = "Curacautín", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 247, NombreComuna = "Curarrehue", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 248, NombreComuna = "Ercilla", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 249, NombreComuna = "Freire", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 250, NombreComuna = "Galvarino", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 251, NombreComuna = "Gorbea", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 252, NombreComuna = "Lautaro", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 253, NombreComuna = "Loncoche", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 254, NombreComuna = "Lonquimay", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 255, NombreComuna = "Los Sauces", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 256, NombreComuna = "Lumaco", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 257, NombreComuna = "Melipeuco", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 258, NombreComuna = "Nueva Imperial", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 259, NombreComuna = "Padre Las Casas", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 260, NombreComuna = "Perquenco", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 261, NombreComuna = "Pitrufquén", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 262, NombreComuna = "Pucón", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 263, NombreComuna = "Purén", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 264, NombreComuna = "Renaico", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 265, NombreComuna = "Saavedra", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 266, NombreComuna = "Temuco", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 267, NombreComuna = "Teodoro Schmidt", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 268, NombreComuna = "Toltén", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 269, NombreComuna = "Traiguén", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 270, NombreComuna = "Victoria", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 271, NombreComuna = "Vilcún", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 272, NombreComuna = "Villarrica", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 273, NombreComuna = "Panguipulli", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { Id = 274, NombreComuna = "Ancud", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 275, NombreComuna = "Calbuco", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 276, NombreComuna = "Castro", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 277, NombreComuna = "Chaitén", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 278, NombreComuna = "Chonchi", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 279, NombreComuna = "Cochamó", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 280, NombreComuna = "Curaco de Vélez", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 281, NombreComuna = "Dalcahue", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 282, NombreComuna = "Fresia", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 283, NombreComuna = "Frutillar", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 284, NombreComuna = "Futaleufú", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 285, NombreComuna = "Hualaihué", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 286, NombreComuna = "Llanquihue", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 287, NombreComuna = "Los Muermos", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 288, NombreComuna = "Maullín", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 289, NombreComuna = "Osorno", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 290, NombreComuna = "Palena", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 291, NombreComuna = "Puerto Montt", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 292, NombreComuna = "Puerto Octay", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 293, NombreComuna = "Puerto Varas", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 294, NombreComuna = "Purranque", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 295, NombreComuna = "Puyehue", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 296, NombreComuna = "Queilén", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 297, NombreComuna = "Quellón", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 298, NombreComuna = "Quemchi", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 299, NombreComuna = "Quinchao", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 300, NombreComuna = "Río Negro", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 301, NombreComuna = "San Juan de la Costa", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 302, NombreComuna = "San Pablo", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 303, NombreComuna = "Toltén", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 304, NombreComuna = "Vilcún", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 305, NombreComuna = "Villarrica", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 306, NombreComuna = "Panguipulli", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { Id = 307, NombreComuna = "Aysén", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { Id = 308, NombreComuna = "Chile Chico", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { Id = 309, NombreComuna = "Cisnes", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { Id = 310, NombreComuna = "Cochrane", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { Id = 311, NombreComuna = "Coyhaique", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { Id = 312, NombreComuna = "Guaitecas", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { Id = 313, NombreComuna = "Lago Verde", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { Id = 314, NombreComuna = "OHiggins", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { Id = 315, NombreComuna = "Río Ibáñez", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { Id = 316, NombreComuna = "Tortel", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { Id = 317, NombreComuna = "Antártica", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { Id = 318, NombreComuna = "Cabo de Hornos", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { Id = 319, NombreComuna = "Laguna Blanca", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { Id = 320, NombreComuna = "Natales", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { Id = 321, NombreComuna = "Porvenir", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { Id = 322, NombreComuna = "Primavera", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { Id = 323, NombreComuna = "Punta Arenas", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { Id = 324, NombreComuna = "Río Verde", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { Id = 325, NombreComuna = "San Gregorio", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { Id = 326, NombreComuna = "Timaukel", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { Id = 327, NombreComuna = "Torres del Paine", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { Id = 328, NombreComuna = "Corral", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { Id = 329, NombreComuna = "Futrono", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { Id = 330, NombreComuna = "La Unión", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { Id = 331, NombreComuna = "Lago Ranco", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { Id = 332, NombreComuna = "Lanco", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { Id = 333, NombreComuna = "Los Lagos", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { Id = 334, NombreComuna = "Máfil", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { Id = 335, NombreComuna = "Mariquina", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { Id = 336, NombreComuna = "Paillaco", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { Id = 337, NombreComuna = "Panguipulli", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { Id = 338, NombreComuna = "Río Bueno", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { Id = 339, NombreComuna = "Valdivia", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { Id = 340, NombreComuna = "Arica", Region = "Región de Arica y Parinacota", SiglaRegion = "XV", EsActivo = true},
                new Comuna { Id = 341, NombreComuna = "Camarones", Region = "Región de Arica y Parinacota", SiglaRegion = "XV", EsActivo = true},
                new Comuna { Id = 342, NombreComuna = "General Lagos", Region = "Región de Arica y Parinacota", SiglaRegion = "XV", EsActivo = true},
                new Comuna { Id = 343, NombreComuna = "Putre", Region = "Región de Arica y Parinacota", SiglaRegion = "XV", EsActivo = true},
                new Comuna { Id = 344, NombreComuna = "Bulnes", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 345, NombreComuna = "Chillán", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 346, NombreComuna = "Chillán Viejo", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 347, NombreComuna = "Cobquecura", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 348, NombreComuna = "Coelemu", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 349, NombreComuna = "Coihueco", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 350, NombreComuna = "El Carmen", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 351, NombreComuna = "Ninhue", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 352, NombreComuna = "Ñiquén", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 353, NombreComuna = "Pemuco", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 354, NombreComuna = "Pinto", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 355, NombreComuna = "Portezuelo", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 356, NombreComuna = "Quillón", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 357, NombreComuna = "Quirihue", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 358, NombreComuna = "Ránquil", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 359, NombreComuna = "San Carlos", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 360, NombreComuna = "San Fabián", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 361, NombreComuna = "San Ignacio", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 362, NombreComuna = "San Nicolás", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 363, NombreComuna = "Treguaco", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { Id = 364, NombreComuna = "Yungay", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true}

            };

            modelBuilder.Entity<Comuna>().HasData(hasData);
        }
    }
}
