namespace AtencionMedica.Infraestructure.Seeders
{
    internal class SeedComuna : ISeed<Comuna>
    {
        public void Seed(ModelBuilder modelBuilder)
        {
            Comuna[] hasData = {
                new Comuna { IdComuna = 1, NombreComuna = "Arica", Region = "Región de Tarapacá", SiglaRegion = "I", EsActivo = true},
                new Comuna { IdComuna = 2, NombreComuna = "Camarones", Region = "Región de Tarapacá", SiglaRegion = "I", EsActivo = true},
                new Comuna { IdComuna = 3, NombreComuna = "Alto Hospicio", Region = "Región de Antofagasta", SiglaRegion = "II", EsActivo = true},
                new Comuna { IdComuna = 4, NombreComuna = "Iquique", Region = "Región de Antofagasta", SiglaRegion = "II", EsActivo = true},
                new Comuna { IdComuna = 5, NombreComuna = "Camiña", Region = "Región de Antofagasta", SiglaRegion = "II", EsActivo = true},
                new Comuna { IdComuna = 6, NombreComuna = "Colchane", Region = "Región de Antofagasta", SiglaRegion = "II", EsActivo = true},
                new Comuna { IdComuna = 7, NombreComuna = "Huara", Region = "Región de Antofagasta", SiglaRegion = "II", EsActivo = true},
                new Comuna { IdComuna = 8, NombreComuna = "Pica", Region = "Región de Antofagasta", SiglaRegion = "II", EsActivo = true},
                new Comuna { IdComuna = 9, NombreComuna = "Pozo Almonte", Region = "Región de Antofagasta", SiglaRegion = "II", EsActivo = true},
                new Comuna { IdComuna = 10, NombreComuna = "Caldera", Region = "Región de Atacama", SiglaRegion = "III", EsActivo = true},
                new Comuna { IdComuna = 11, NombreComuna = "Chanaral", Region = "Región de Atacama", SiglaRegion = "III", EsActivo = true},
                new Comuna { IdComuna = 12, NombreComuna = "Copiapó", Region = "Región de Atacama", SiglaRegion = "III", EsActivo = true},
                new Comuna { IdComuna = 13, NombreComuna = "Diego de Almagro", Region = "Región de Atacama", SiglaRegion = "III", EsActivo = true},
                new Comuna { IdComuna = 14, NombreComuna = "Freirina", Region = "Región de Atacama", SiglaRegion = "III", EsActivo = true},
                new Comuna { IdComuna = 15, NombreComuna = "Huasco", Region = "Región de Atacama", SiglaRegion = "III", EsActivo = true},
                new Comuna { IdComuna = 16, NombreComuna = "Tierra Amarilla", Region = "Región de Atacama", SiglaRegion = "III", EsActivo = true},
                new Comuna { IdComuna = 17, NombreComuna = "Vallenar", Region = "Región de Atacama", SiglaRegion = "III", EsActivo = true},
                new Comuna { IdComuna = 18, NombreComuna = "Andacollo", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { IdComuna = 19, NombreComuna = "Canela", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { IdComuna = 20, NombreComuna = "Combarbalá", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},

                new Comuna { IdComuna = 21, NombreComuna = "Coquimbo", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { IdComuna = 22, NombreComuna = "Illapel", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { IdComuna = 23, NombreComuna = "La Higuera", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { IdComuna = 24, NombreComuna = "La Serena", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { IdComuna = 25, NombreComuna = "Los Vilos", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { IdComuna = 26, NombreComuna = "Monte Patria", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { IdComuna = 27, NombreComuna = "Ovalle", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { IdComuna = 28, NombreComuna = "Paihuano", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { IdComuna = 29, NombreComuna = "Punitaqui", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { IdComuna = 30, NombreComuna = "Río Hurtado", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { IdComuna = 31, NombreComuna = "Salamanca", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { IdComuna = 32, NombreComuna = "Vicuña", Region = "Región de Coquimbo", SiglaRegion = "IV", EsActivo = true},
                new Comuna { IdComuna = 33, NombreComuna = "Algarrobo", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 34, NombreComuna = "Cabildo", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 35, NombreComuna = "Calera", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 36, NombreComuna = "Calle Larga", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 37, NombreComuna = "Cartagena", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 38, NombreComuna = "Casablanca", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 39, NombreComuna = "Catemu", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 40, NombreComuna = "Concón", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},

                new Comuna { IdComuna = 41, NombreComuna = "El Quisco", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 42, NombreComuna = "El Tabo", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 43, NombreComuna = "Hijuelas", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 44, NombreComuna = "Isla de Pascua", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 45, NombreComuna = "Juan Fernández", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 46, NombreComuna = "La Cruz", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 47, NombreComuna = "La Ligua", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 48, NombreComuna = "Limache", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 49, NombreComuna = "Llaillay", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 50, NombreComuna = "Los Andes", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 51, NombreComuna = "Nogales", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 52, NombreComuna = "Olmué", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 53, NombreComuna = "Panquehue", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 54, NombreComuna = "Papudo", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 55, NombreComuna = "Petorca", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 56, NombreComuna = "Puchuncaví", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 57, NombreComuna = "Putaendo", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 58, NombreComuna = "Quillota", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 59, NombreComuna = "Quilpué", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 60, NombreComuna = "Quintero", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 61, NombreComuna = "Rinconada", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 62, NombreComuna = "San Antonio", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 63, NombreComuna = "San Esteban", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 64, NombreComuna = "San Felipe", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 65, NombreComuna = "Santa María", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 66, NombreComuna = "Santo Domingo", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 67, NombreComuna = "Valparaíso", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 68, NombreComuna = "Villa Alemana", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 69, NombreComuna = "Viña del Mar", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 70, NombreComuna = "Zapallar", Region = "Región de Valparaíso", SiglaRegion = "V", EsActivo = true},
                new Comuna { IdComuna = 71, NombreComuna = "Alhué", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 72, NombreComuna = "Buin", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 73, NombreComuna = "Calera de Tango", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 74, NombreComuna = "Cerrillos", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 75, NombreComuna = "Cerro Navia", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 76, NombreComuna = "Colina", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 77, NombreComuna = "Conchalí", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 78, NombreComuna = "Curacaví", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 79, NombreComuna = "El Bosque", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 80, NombreComuna = "El Monte", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 81, NombreComuna = "Estación Central", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 82, NombreComuna = "Huechuraba", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 83, NombreComuna = "Independencia", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 84, NombreComuna = "Isla de Maipo", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 85, NombreComuna = "La Cisterna", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 86, NombreComuna = "La Florida", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 87, NombreComuna = "La Granja", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 88, NombreComuna = "La Pintana", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 89, NombreComuna = "La Reina", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 90, NombreComuna = "Lampa", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 91, NombreComuna = "Las Condes", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 92, NombreComuna = "Lo Barnechea", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 93, NombreComuna = "Lo Espejo", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 94, NombreComuna = "Lo Prado", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 95, NombreComuna = "Macul", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 96, NombreComuna = "Maipú", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 97, NombreComuna = "María Pinto", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 98, NombreComuna = "Melipilla", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 99, NombreComuna = "Ñuñoa", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 100, NombreComuna = "Padre Hurtado", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},

                new Comuna { IdComuna = 101, NombreComuna = "Paine", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 102, NombreComuna = "Pedro Aguirre Cerda", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 103, NombreComuna = "Peñaflor", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 104, NombreComuna = "Peñalolén", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 105, NombreComuna = "Pirque", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 106, NombreComuna = "Providencia", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 107, NombreComuna = "Pudahuel", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 108, NombreComuna = "Puente Alto", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 109, NombreComuna = "Quilicura", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 110, NombreComuna = "Quinta Normal", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 111, NombreComuna = "Recoleta", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 112, NombreComuna = "Renca", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 113, NombreComuna = "San Bernardo", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 114, NombreComuna = "San Joaquín", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 115, NombreComuna = "San José de Maipo", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 116, NombreComuna = "San Miguel", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 117, NombreComuna = "San Pedro", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 118, NombreComuna = "San Ramón", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 119, NombreComuna = "Santiago", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 120, NombreComuna = "Talagante", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 121, NombreComuna = "Tiltil", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 122, NombreComuna = "Vitacura", Region = "Región Metropolitana de Santiago", SiglaRegion = "RM", EsActivo = true},
                new Comuna { IdComuna = 123, NombreComuna = "Cachapoal", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 124, NombreComuna = "Cardenal Caro", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 125, NombreComuna = "Chépica", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 126, NombreComuna = "Chimbarongo", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 127, NombreComuna = "Codegua", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 128, NombreComuna = "Coinco", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 129, NombreComuna = "Coltauco", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 130, NombreComuna = "Doñihue", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 131, NombreComuna = "Graneros", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 132, NombreComuna = "La Estrella", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 133, NombreComuna = "Las Cabras", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 134, NombreComuna = "Litueche", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 135, NombreComuna = "Lolol", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 136, NombreComuna = "Machalí", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 137, NombreComuna = "Malloa", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 138, NombreComuna = "Marchihue", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 139, NombreComuna = "Nancagua", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 140, NombreComuna = "Navidad", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 141, NombreComuna = "Olivar", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 142, NombreComuna = "Palmilla", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 143, NombreComuna = "Paredones", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 144, NombreComuna = "Peralillo", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 145, NombreComuna = "Peumo", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 146, NombreComuna = "Pichidegua", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 147, NombreComuna = "Pichilemu", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 148, NombreComuna = "Placilla", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 149, NombreComuna = "Pumanque", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 150, NombreComuna = "Quinta de Tilcoco", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 151, NombreComuna = "Rancagua", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 152, NombreComuna = "Rengo", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 153, NombreComuna = "Requínoa", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 154, NombreComuna = "San Fernando", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 155, NombreComuna = "San Vicente de Tagua Tagua", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 156, NombreComuna = "Santa Cruz", Region = "Región del Libertador General Bernardo O'Higgins", SiglaRegion = "VI", EsActivo = true},
                new Comuna { IdComuna = 157, NombreComuna = "Cauquenes", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 158, NombreComuna = "Chanco", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 159, NombreComuna = "Colbún", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 160, NombreComuna = "Constitución", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 161, NombreComuna = "Curepto", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 162, NombreComuna = "Curicó", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 163, NombreComuna = "Empedrado", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 164, NombreComuna = "Hualañé", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 165, NombreComuna = "Licantén", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 166, NombreComuna = "Linares", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 167, NombreComuna = "Longaví", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 168, NombreComuna = "Maule", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 169, NombreComuna = "Molina", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 170, NombreComuna = "Parral", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 171, NombreComuna = "Pelarco", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 172, NombreComuna = "Pelluhue", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 173, NombreComuna = "Pencahue", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 174, NombreComuna = "Rauco", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 175, NombreComuna = "Retiro", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 176, NombreComuna = "Romeral", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 177, NombreComuna = "Sagrada Familia", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 178, NombreComuna = "San Clemente", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 179, NombreComuna = "San Javier", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 180, NombreComuna = "San Rafael", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 181, NombreComuna = "Santa Cruz", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 182, NombreComuna = "Talca", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 183, NombreComuna = "Teno", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 184, NombreComuna = "Vichuquén", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 185, NombreComuna = "Villa Alegre", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 186, NombreComuna = "Yerbas Buenas", Region = "Región del Maule", SiglaRegion = "VII", EsActivo = true},
                new Comuna { IdComuna = 187, NombreComuna = "Alto Biobío", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 188, NombreComuna = "Antuco", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 189, NombreComuna = "Arauco", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 190, NombreComuna = "Bulnes", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},

                new Comuna { IdComuna = 191, NombreComuna = "Cabrero", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 192, NombreComuna = "Cañete", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 193, NombreComuna = "Chiguayante", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 194, NombreComuna = "Chillán", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 195, NombreComuna = "Chillán Viejo", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 196, NombreComuna = "Cobquecura", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 197, NombreComuna = "Coelemu", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 198, NombreComuna = "Coihueco", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 199, NombreComuna = "Concepción", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 200, NombreComuna = "Contulmo", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 201, NombreComuna = "Coronel", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 202, NombreComuna = "Curanilahue", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 203, NombreComuna = "El Carmen", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 204, NombreComuna = "Florida", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 205, NombreComuna = "Hualpén", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 206, NombreComuna = "Hualqui", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 207, NombreComuna = "Laja", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 208, NombreComuna = "Lebu", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 209, NombreComuna = "Los Álamos", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 210, NombreComuna = "Los Ángeles", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},

                new Comuna { IdComuna = 211, NombreComuna = "Lota", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 212, NombreComuna = "Mulchén", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 213, NombreComuna = "Nacimiento", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 214, NombreComuna = "Negrete", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 215, NombreComuna = "Ninhue", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 216, NombreComuna = "Ñiquén", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 217, NombreComuna = "Pemuco", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 218, NombreComuna = "Penco", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 219, NombreComuna = "Pinto", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 220, NombreComuna = "Portezuelo", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 221, NombreComuna = "Quilaco", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 222, NombreComuna = "Quilleco", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 223, NombreComuna = "Quillón", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 224, NombreComuna = "Quirihue", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 225, NombreComuna = "Ránquil", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 226, NombreComuna = "San Carlos", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 227, NombreComuna = "San Fabián", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 228, NombreComuna = "San Ignacio", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 229, NombreComuna = "San Nicolás", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 230, NombreComuna = "San Pedro de la Paz", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 231, NombreComuna = "San Rosendo", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 232, NombreComuna = "Santa Bárbara", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 233, NombreComuna = "Santa Juana", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 234, NombreComuna = "Talcahuano", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 235, NombreComuna = "Tirúa", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 236, NombreComuna = "Tomé", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 237, NombreComuna = "Treguaco", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 238, NombreComuna = "Tucapel", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 239, NombreComuna = "Yumbel", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 240, NombreComuna = "Yungay", Region = "Región del Biobío", SiglaRegion = "VIII", EsActivo = true},
                new Comuna { IdComuna = 241, NombreComuna = "Angol", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 242, NombreComuna = "Carahue", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 243, NombreComuna = "Cholchol", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 244, NombreComuna = "Collipulli", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 245, NombreComuna = "Cunco", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 246, NombreComuna = "Curacautín", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 247, NombreComuna = "Curarrehue", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 248, NombreComuna = "Ercilla", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 249, NombreComuna = "Freire", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 250, NombreComuna = "Galvarino", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 251, NombreComuna = "Gorbea", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 252, NombreComuna = "Lautaro", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 253, NombreComuna = "Loncoche", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 254, NombreComuna = "Lonquimay", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 255, NombreComuna = "Los Sauces", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 256, NombreComuna = "Lumaco", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 257, NombreComuna = "Melipeuco", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 258, NombreComuna = "Nueva Imperial", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 259, NombreComuna = "Padre Las Casas", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 260, NombreComuna = "Perquenco", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 261, NombreComuna = "Pitrufquén", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 262, NombreComuna = "Pucón", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 263, NombreComuna = "Purén", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 264, NombreComuna = "Renaico", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 265, NombreComuna = "Saavedra", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 266, NombreComuna = "Temuco", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 267, NombreComuna = "Teodoro Schmidt", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 268, NombreComuna = "Toltén", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 269, NombreComuna = "Traiguén", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 270, NombreComuna = "Victoria", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 271, NombreComuna = "Vilcún", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 272, NombreComuna = "Villarrica", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 273, NombreComuna = "Panguipulli", Region = "Región de La Araucanía", SiglaRegion = "IX", EsActivo = true},
                new Comuna { IdComuna = 274, NombreComuna = "Ancud", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 275, NombreComuna = "Calbuco", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 276, NombreComuna = "Castro", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 277, NombreComuna = "Chaitén", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 278, NombreComuna = "Chonchi", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 279, NombreComuna = "Cochamó", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 280, NombreComuna = "Curaco de Vélez", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 281, NombreComuna = "Dalcahue", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 282, NombreComuna = "Fresia", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 283, NombreComuna = "Frutillar", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 284, NombreComuna = "Futaleufú", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 285, NombreComuna = "Hualaihué", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 286, NombreComuna = "Llanquihue", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 287, NombreComuna = "Los Muermos", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 288, NombreComuna = "Maullín", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 289, NombreComuna = "Osorno", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 290, NombreComuna = "Palena", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 291, NombreComuna = "Puerto Montt", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 292, NombreComuna = "Puerto Octay", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 293, NombreComuna = "Puerto Varas", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 294, NombreComuna = "Purranque", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 295, NombreComuna = "Puyehue", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 296, NombreComuna = "Queilén", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 297, NombreComuna = "Quellón", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 298, NombreComuna = "Quemchi", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 299, NombreComuna = "Quinchao", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 300, NombreComuna = "Río Negro", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 301, NombreComuna = "San Juan de la Costa", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 302, NombreComuna = "San Pablo", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 303, NombreComuna = "Toltén", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 304, NombreComuna = "Vilcún", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 305, NombreComuna = "Villarrica", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 306, NombreComuna = "Panguipulli", Region = "Región de Los Lagos", SiglaRegion = "X", EsActivo = true},
                new Comuna { IdComuna = 307, NombreComuna = "Aysén", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { IdComuna = 308, NombreComuna = "Chile Chico", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { IdComuna = 309, NombreComuna = "Cisnes", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { IdComuna = 310, NombreComuna = "Cochrane", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { IdComuna = 311, NombreComuna = "Coyhaique", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { IdComuna = 312, NombreComuna = "Guaitecas", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { IdComuna = 313, NombreComuna = "Lago Verde", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { IdComuna = 314, NombreComuna = "OHiggins", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { IdComuna = 315, NombreComuna = "Río Ibáñez", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { IdComuna = 316, NombreComuna = "Tortel", Region = "Región de Aysén del General Carlos Ibáñez del Campo", SiglaRegion = "XI", EsActivo = true},
                new Comuna { IdComuna = 317, NombreComuna = "Antártica", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { IdComuna = 318, NombreComuna = "Cabo de Hornos", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { IdComuna = 319, NombreComuna = "Laguna Blanca", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { IdComuna = 320, NombreComuna = "Natales", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { IdComuna = 321, NombreComuna = "Porvenir", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { IdComuna = 322, NombreComuna = "Primavera", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { IdComuna = 323, NombreComuna = "Punta Arenas", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { IdComuna = 324, NombreComuna = "Río Verde", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { IdComuna = 325, NombreComuna = "San Gregorio", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { IdComuna = 326, NombreComuna = "Timaukel", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { IdComuna = 327, NombreComuna = "Torres del Paine", Region = "Región de Magallanes y de la Antártica Chilena", SiglaRegion = "XII", EsActivo = true},
                new Comuna { IdComuna = 328, NombreComuna = "Corral", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { IdComuna = 329, NombreComuna = "Futrono", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { IdComuna = 330, NombreComuna = "La Unión", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { IdComuna = 331, NombreComuna = "Lago Ranco", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { IdComuna = 332, NombreComuna = "Lanco", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { IdComuna = 333, NombreComuna = "Los Lagos", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { IdComuna = 334, NombreComuna = "Máfil", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { IdComuna = 335, NombreComuna = "Mariquina", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { IdComuna = 336, NombreComuna = "Paillaco", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { IdComuna = 337, NombreComuna = "Panguipulli", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { IdComuna = 338, NombreComuna = "Río Bueno", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { IdComuna = 339, NombreComuna = "Valdivia", Region = "Región de Los Ríos", SiglaRegion = "XIV", EsActivo = true},
                new Comuna { IdComuna = 340, NombreComuna = "Arica", Region = "Región de Arica y Parinacota", SiglaRegion = "XV", EsActivo = true},
                new Comuna { IdComuna = 341, NombreComuna = "Camarones", Region = "Región de Arica y Parinacota", SiglaRegion = "XV", EsActivo = true},
                new Comuna { IdComuna = 342, NombreComuna = "General Lagos", Region = "Región de Arica y Parinacota", SiglaRegion = "XV", EsActivo = true},
                new Comuna { IdComuna = 343, NombreComuna = "Putre", Region = "Región de Arica y Parinacota", SiglaRegion = "XV", EsActivo = true},
                new Comuna { IdComuna = 344, NombreComuna = "Bulnes", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 345, NombreComuna = "Chillán", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 346, NombreComuna = "Chillán Viejo", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 347, NombreComuna = "Cobquecura", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 348, NombreComuna = "Coelemu", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 349, NombreComuna = "Coihueco", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 350, NombreComuna = "El Carmen", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 351, NombreComuna = "Ninhue", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 352, NombreComuna = "Ñiquén", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 353, NombreComuna = "Pemuco", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 354, NombreComuna = "Pinto", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 355, NombreComuna = "Portezuelo", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 356, NombreComuna = "Quillón", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 357, NombreComuna = "Quirihue", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 358, NombreComuna = "Ránquil", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 359, NombreComuna = "San Carlos", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 360, NombreComuna = "San Fabián", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 361, NombreComuna = "San Ignacio", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 362, NombreComuna = "San Nicolás", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 363, NombreComuna = "Treguaco", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true},
                new Comuna { IdComuna = 364, NombreComuna = "Yungay", Region = "Región de Ñuble", SiglaRegion = "XVI", EsActivo = true}

            };

            modelBuilder.Entity<Comuna>().HasData(hasData);
        }
    }
}
