global using Microsoft.EntityFrameworkCore;
global using AtencionMedica.Domain.Entities;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using AtencionMedica.Infraestructure.Options;
global using AtencionMedica.Infraestructure.Data;
global using Microsoft.EntityFrameworkCore.Migrations;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using static AtencionMedica.Infraestructure.Seeders.Interfaces.ISeed;
global using AtencionMedica.Infraestructure.Seeders.Interfaces;
global using AtencionMedica.Domain.Interfaces;
global using AtencionMedica.Infraestructure.Repositories;
global using AtencionMedica.Infraestructure.Seeders;
global using AutoMapper;
global using AtencionMedica.Application.Interfaces;